### PR TITLE
Add `CljfmtRange` function to format from visual selection

### PR DESCRIPTION
**Pull request by erthalion**
I assume it should be enough for #9 . So far I tested it only myself, so I'll be happy to receive any feedback.

### CODE REVIEW

**Comment by venantius** [comment]
Huh. Cool! Can you add a note about this to the README?

**Comment by erthalion** [comment]
@venantius done

**Comment by venantius** [comment]
Thanks!

**Comment by sushovannits** [comment]
@erthalion Great PR. Needed this. Can the vim help doc be updated as well?
And unfortunately does not work on mine. I have pulled the changes.

**Comment by ncharchut** [comment]
As of later today, this is no longer working for me, either. `vim` is convinced that `CljfmtRange` is not an editor command? And yet the other commands seem to work fine. I even verified that `cljfmt.vim` contained the command definition and it does! Any reason this could be happening?

**Pull request merged**
